import { Container, Section } from '@/components'
import { useI18n } from '@/i18n'
import Layout from '@/layouts/Default'

export const TermsPage = () => {
  const { t } = useI18n(localI18n)

  return (
    <Layout
      header={{
        icon: {
          name: 'Document',
          color: 'text-default-400',
        },
        color: 'bg-default-50',
        title: t('Terms of Service'),
        subtitle: t('Usage terms and conditions'),
      }}
    >
      <Section>
        <Container className="markdown-content prose dark:prose-invert max-w-3xl">
          <h2>{t('Terms of Service')}</h2>
          <p>
            <strong>{t('Last updated: January 2026')}</strong>
          </p>
          <p>{t('By using DEVS, you agree to these terms.')}</p>

          <h3>{t('License')}</h3>
          <p>
            {t('DEVS is open-source software released under the')}{' '}
            <strong>{t('MIT License')}</strong>.{' '}
            {t('You are free to use, modify, and distribute the software.')}
          </p>

          <h3>{t('Use at Your Own Risk')}</h3>
          <p>
            {t(
              'DEVS is provided "as is" without warranty of any kind. The software is experimental and:',
            )}
          </p>
          <ul>
            <li>{t('May contain bugs or errors')}</li>
            <li>{t('AI-generated content may be inaccurate')}</li>
            <li>
              {t('We are not responsible for any damages arising from use')}
            </li>
          </ul>

          <h3>{t('Your Responsibilities')}</h3>
          <p>{t('You are responsible for:')}</p>
          <ul>
            <li>{t('Your API keys and their associated costs')}</li>
            <li>{t('Content you generate using the platform')}</li>
            <li>{t('Compliance with LLM provider terms of service')}</li>
            <li>{t('Ensuring generated content meets your local laws')}</li>
          </ul>

          <h3>{t('AI-Generated Content')}</h3>
          <p>{t('Content generated by AI agents:')}</p>
          <ul>
            <li>{t('Should be reviewed before use')}</li>
            <li>{t('May require fact-checking')}</li>
            <li>{t('Does not represent our views or opinions')}</li>
          </ul>

          <h3>{t('Changes')}</h3>
          <p>
            {t(
              'We may update these terms at any time. Continued use constitutes acceptance of changes.',
            )}
          </p>

          <h3>{t('Contact')}</h3>
          <p>
            {t('For questions, open an issue on our')}{' '}
            <a href="https://github.com/codename-co/devs">
              {t('GitHub repository')}
            </a>
            .
          </p>
        </Container>
      </Section>
    </Layout>
  )
}

const localI18n = {
  en: [
    'Terms of Service',
    'Usage terms and conditions',
    'Last updated: January 2026',
    'By using DEVS, you agree to these terms.',
    'License',
    'DEVS is open-source software released under the',
    'MIT License',
    'You are free to use, modify, and distribute the software.',
    'Use at Your Own Risk',
    'DEVS is provided "as is" without warranty of any kind. The software is experimental and:',
    'May contain bugs or errors',
    'AI-generated content may be inaccurate',
    'We are not responsible for any damages arising from use',
    'Your Responsibilities',
    'You are responsible for:',
    'Your API keys and their associated costs',
    'Content you generate using the platform',
    'Compliance with LLM provider terms of service',
    'Ensuring generated content meets your local laws',
    'AI-Generated Content',
    'Content generated by AI agents:',
    'Should be reviewed before use',
    'May require fact-checking',
    'Does not represent our views or opinions',
    'Changes',
    'We may update these terms at any time. Continued use constitutes acceptance of changes.',
    'Contact',
    'For questions, open an issue on our',
    'GitHub repository',
  ] as const,
  ar: {
    'Terms of Service': 'شروط الخدمة',
    'Usage terms and conditions': 'شروط وأحكام الاستخدام',
    'Last updated: January 2026': 'آخر تحديث: يناير 2026',
    'By using DEVS, you agree to these terms.':
      'باستخدامك DEVS، فإنك توافق على هذه الشروط.',
    License: 'الترخيص',
    'DEVS is open-source software released under the':
      'DEVS هو برنامج مفتوح المصدر تم إصداره بموجب',
    'MIT License': 'رخصة MIT',
    'You are free to use, modify, and distribute the software.':
      'يحق لك استخدام البرنامج وتعديله وتوزيعه بحرية.',
    'Use at Your Own Risk': 'الاستخدام على مسؤوليتك الخاصة',
    'DEVS is provided "as is" without warranty of any kind. The software is experimental and:':
      'يتم توفير DEVS "كما هو" دون أي ضمان من أي نوع. البرنامج تجريبي وقد:',
    'May contain bugs or errors': 'يحتوي على أخطاء أو مشاكل',
    'AI-generated content may be inaccurate':
      'قد يكون المحتوى الذي أنشأه الذكاء الاصطناعي غير دقيق',
    'We are not responsible for any damages arising from use':
      'لسنا مسؤولين عن أي أضرار ناتجة عن الاستخدام',
    'Your Responsibilities': 'مسؤولياتك',
    'You are responsible for:': 'أنت مسؤول عن:',
    'Your API keys and their associated costs':
      'مفاتيح API الخاصة بك وتكاليفها المرتبطة',
    'Content you generate using the platform':
      'المحتوى الذي تنشئه باستخدام المنصة',
    'Compliance with LLM provider terms of service': 'الامتثال لشروط مزودي LLM',
    'Ensuring generated content meets your local laws':
      'ضمان أن المحتوى المولد يلتزم بقوانينك المحلية',
    'AI-Generated Content': 'محتوى تم إنشاؤه بواسطة الذكاء الاصطناعي',
    'Content generated by AI agents:':
      'المحتوى الذي ينشئه وكلاء الذكاء الاصطناعي:',
    'Should be reviewed before use': 'يجب مراجعته قبل الاستخدام',
    'May require fact-checking': 'قد يتطلب التحقق من الحقائق',
    'Does not represent our views or opinions': 'لا يمثل وجهات نظرنا أو آرائنا',
    Changes: 'التغييرات',
    'We may update these terms at any time. Continued use constitutes acceptance of changes.':
      'قد نقوم بتحديث هذه الشروط في أي وقت. استمرار الاستخدام يعني قبول التغييرات.',
    Contact: 'اتصل',
    'For questions, open an issue on our': 'للاستفسارات، افتح تذكرة في',
    'GitHub repository': 'مستودع GitHub',
  },
  de: {
    'Terms of Service': 'Nutzungsbedingungen',
    'Usage terms and conditions': 'Nutzungsbedingungen und Konditionen',
    'Last updated: January 2026': 'Zuletzt aktualisiert: Januar 2026',
    'By using DEVS, you agree to these terms.':
      'Durch die Nutzung von DEVS stimmen Sie diesen Bedingungen zu.',
    License: 'Lizenz',
    'DEVS is open-source software released under the':
      'DEVS ist Open-Source-Software, veröffentlicht unter der',
    'MIT License': 'MIT-Lizenz',
    'You are free to use, modify, and distribute the software.':
      'Sie dürfen die Software frei verwenden, modifizieren und weitergeben.',
    'Use at Your Own Risk': 'Nutzung auf eigene Gefahr',
    'DEVS is provided "as is" without warranty of any kind. The software is experimental and:':
      'DEVS wird ohne jegliche Gewährleistung bereitgestellt. Die Software ist experimentell und:',
    'May contain bugs or errors': 'Kann Fehler oder Bugs enthalten',
    'AI-generated content may be inaccurate':
      'KI-generierte Inhalte können ungenau sein',
    'We are not responsible for any damages arising from use':
      'Wir übernehmen keine Haftung für Schäden aus der Nutzung',
    'Your Responsibilities': 'Ihre Verantwortlichkeiten',
    'You are responsible for:': 'Sie sind verantwortlich für:',
    'Your API keys and their associated costs':
      'Ihre API-Schlüssel und die damit verbundenen Kosten',
    'Content you generate using the platform':
      'Inhalte, die Sie mit der Plattform generieren',
    'Compliance with LLM provider terms of service':
      'Einhaltung der Bedingungen der LLM-Anbieter',
    'Ensuring generated content meets your local laws':
      'Sicherstellung, dass generierte Inhalte Ihren lokalen Gesetzen entsprechen',
    'AI-Generated Content': 'KI-generierte Inhalte',
    'Content generated by AI agents:': 'Von KI-Agenten generierte Inhalte:',
    'Should be reviewed before use': 'Sollten vor der Nutzung überprüft werden',
    'May require fact-checking': 'Kann Faktenüberprüfung erfordern',
    'Does not represent our views or opinions':
      'Stellt nicht unsere Ansichten oder Meinungen dar',
    Changes: 'Änderungen',
    'We may update these terms at any time. Continued use constitutes acceptance of changes.':
      'Wir können diese Bedingungen jederzeit aktualisieren. Die fortgesetzte Nutzung gilt als Zustimmung zu den Änderungen.',
    Contact: 'Kontakt',
    'For questions, open an issue on our':
      'Bei Fragen öffnen Sie bitte ein Issue in unserem',
    'GitHub repository': 'GitHub-Repository',
  },
  es: {
    'Terms of Service': 'Términos de servicio',
    'Usage terms and conditions': 'Términos y condiciones de uso',
    'Last updated: January 2026': 'Última actualización: enero de 2026',
    'By using DEVS, you agree to these terms.':
      'Al usar DEVS, aceptas estos términos.',
    License: 'Licencia',
    'DEVS is open-source software released under the':
      'DEVS es software de código abierto publicado bajo la',
    'MIT License': 'Licencia MIT',
    'You are free to use, modify, and distribute the software.':
      'Eres libre de usar, modificar y distribuir el software.',
    'Use at Your Own Risk': 'Uso bajo tu propio riesgo',
    'DEVS is provided "as is" without warranty of any kind. The software is experimental and:':
      'DEVS se proporciona "tal cual" sin garantía de ningún tipo. El software es experimental y:',
    'May contain bugs or errors': 'Puede contener errores o fallos',
    'AI-generated content may be inaccurate':
      'El contenido generado por IA puede ser inexacto',
    'We are not responsible for any damages arising from use':
      'No somos responsables de los daños derivados del uso',
    'Your Responsibilities': 'Tus responsabilidades',
    'You are responsible for:': 'Eres responsable de:',
    'Your API keys and their associated costs':
      'Tus claves API y sus costes asociados',
    'Content you generate using the platform':
      'El contenido que generes usando la plataforma',
    'Compliance with LLM provider terms of service':
      'Cumplimiento de los términos de los proveedores LLM',
    'Ensuring generated content meets your local laws':
      'Asegurarte de que el contenido generado cumpla tus leyes locales',
    'AI-Generated Content': 'Contenido generado por IA',
    'Content generated by AI agents:': 'El contenido generado por agentes IA:',
    'Should be reviewed before use': 'Debe revisarse antes de usar',
    'May require fact-checking': 'Puede requerir verificación de hechos',
    'Does not represent our views or opinions':
      'No representa nuestras opiniones o puntos de vista',
    Changes: 'Cambios',
    'We may update these terms at any time. Continued use constitutes acceptance of changes.':
      'Podemos actualizar estos términos en cualquier momento. El uso continuado constituye aceptación de los cambios.',
    Contact: 'Contacto',
    'For questions, open an issue on our':
      'Para preguntas, abre un issue en nuestro',
    'GitHub repository': 'repositorio de GitHub',
  },
  fr: {
    'Terms of Service': "Conditions d'utilisation",
    'Usage terms and conditions': "Termes et conditions d'utilisation",
    'Last updated: January 2026': 'Dernière mise à jour : janvier 2026',
    'By using DEVS, you agree to these terms.':
      'En utilisant DEVS, vous acceptez ces conditions.',
    License: 'Licence',
    'DEVS is open-source software released under the':
      'DEVS est un logiciel open-source publié sous',
    'MIT License': 'Licence MIT',
    'You are free to use, modify, and distribute the software.':
      "Vous êtes libre d'utiliser, modifier et distribuer le logiciel.",
    'Use at Your Own Risk': 'Utilisation à vos risques',
    'DEVS is provided "as is" without warranty of any kind. The software is experimental and:':
      'DEVS est fourni "tel quel" sans aucune garantie. Le logiciel est expérimental et :',
    'May contain bugs or errors': 'Peut contenir des bugs ou erreurs',
    'AI-generated content may be inaccurate':
      "Le contenu généré par l'IA peut être inexact",
    'We are not responsible for any damages arising from use':
      "Nous ne sommes pas responsables des dommages résultant de l'utilisation",
    'Your Responsibilities': 'Vos responsabilités',
    'You are responsible for:': 'Vous êtes responsable de :',
    'Your API keys and their associated costs':
      'Vos clés API et leurs coûts associés',
    'Content you generate using the platform':
      'Le contenu que vous générez avec la plateforme',
    'Compliance with LLM provider terms of service':
      'La conformité avec les conditions des fournisseurs LLM',
    'Ensuring generated content meets your local laws':
      "S'assurer que le contenu généré respecte vos lois locales",
    'AI-Generated Content': "Contenu généré par l'IA",
    'Content generated by AI agents:': 'Le contenu généré par les agents IA :',
    'Should be reviewed before use': 'Doit être vérifié avant utilisation',
    'May require fact-checking': 'Peut nécessiter une vérification des faits',
    'Does not represent our views or opinions':
      'Ne représente pas nos points de vue ou opinions',
    Changes: 'Modifications',
    'We may update these terms at any time. Continued use constitutes acceptance of changes.':
      "Nous pouvons mettre à jour ces conditions à tout moment. L'utilisation continue constitue une acceptation des modifications.",
    Contact: 'Contact',
    'For questions, open an issue on our':
      'Pour toute question, ouvrez une issue sur notre',
    'GitHub repository': 'dépôt GitHub',
  },
  ko: {
    'Terms of Service': '이용 약관',
    'Usage terms and conditions': '이용 조건 및 약관',
    'Last updated: January 2026': '최종 업데이트: 2026년 1월',
    'By using DEVS, you agree to these terms.':
      'DEVS를 사용함으로써 귀하는 본 약관에 동의하게 됩니다.',
    License: '라이선스',
    'DEVS is open-source software released under the':
      'DEVS는 오픈소스 소프트웨어로 다음 라이선스 하에 배포됩니다:',
    'MIT License': 'MIT 라이선스',
    'You are free to use, modify, and distribute the software.':
      '소프트웨어를 자유롭게 사용, 수정, 배포할 수 있습니다.',
    'Use at Your Own Risk': '본인 책임하에 사용',
    'DEVS is provided "as is" without warranty of any kind. The software is experimental and:':
      'DEVS는 어떠한 보증도 없이 "있는 그대로" 제공됩니다. 소프트웨어는 실험적이며:',
    'May contain bugs or errors': '버그 또는 오류가 있을 수 있음',
    'AI-generated content may be inaccurate':
      'AI가 생성한 내용이 부정확할 수 있음',
    'We are not responsible for any damages arising from use':
      '사용으로 인한 손해에 대해 책임지지 않습니다',
    'Your Responsibilities': '귀하의 책임',
    'You are responsible for:': '귀하는 다음에 대해 책임이 있습니다:',
    'Your API keys and their associated costs': '귀하의 API 키 및 관련 비용',
    'Content you generate using the platform': '플랫폼을 통해 생성한 콘텐츠',
    'Compliance with LLM provider terms of service': 'LLM 공급자 약관 준수',
    'Ensuring generated content meets your local laws':
      '생성된 콘텐츠가 귀하의 현지 법률을 준수하는지 확인',
    'AI-Generated Content': 'AI 생성 콘텐츠',
    'Content generated by AI agents:': 'AI 에이전트가 생성한 콘텐츠:',
    'Should be reviewed before use': '사용 전 반드시 검토해야 함',
    'May require fact-checking': '사실 확인이 필요할 수 있음',
    'Does not represent our views or opinions':
      '당사의 견해나 의견을 대변하지 않음',
    Changes: '변경사항',
    'We may update these terms at any time. Continued use constitutes acceptance of changes.':
      '본 약관은 언제든지 변경될 수 있으며, 계속 사용 시 변경에 동의하는 것으로 간주됩니다.',
    Contact: '문의',
    'For questions, open an issue on our':
      '문의사항은 다음에서 이슈를 등록하세요:',
    'GitHub repository': 'GitHub 저장소',
  },
}
