import { Container, Section } from '@/components'
import { useI18n } from '@/i18n'
import Layout from '@/layouts/Default'

export const TermsPage = () => {
  const { t, lang } = useI18n(localI18n)

  const lastUpdated = new Intl.DateTimeFormat(lang, {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  }).format(new Date('2026-02-08'))

  return (
    <Layout
      header={{
        icon: {
          name: 'Document',
          color: 'text-default-300 dark:text-default-400',
        },
        color: 'bg-default-50',
        title: t('Terms of Service'),
        subtitle: t('Usage terms and conditions'),
      }}
    >
      <Section>
        <Container className="markdown-content prose dark:prose-invert max-w-3xl">
          <h2>{t('Terms of Service')}</h2>
          <p>
            <strong>{t('Last updated: {date}', { date: lastUpdated })}</strong>
          </p>
          <p>{t('By using DEVS, you agree to these terms.')}</p>

          <h3>{t('License')}</h3>
          <p>
            {t('DEVS is open-source software released under the')}{' '}
            <strong>{t('MIT License')}</strong>.{' '}
            {t('You are free to use, modify, and distribute the software.')}
          </p>

          <h3>{t('Data & Security')}</h3>
          <p>{t('Your data is protected by browser-native encryption:')}</p>
          <ul>
            <li>
              {t(
                'All credentials and sensitive content are encrypted at rest with AES-GCM-256',
              )}
            </li>
            <li>
              {t(
                'Encryption keys are non-extractable and device-bound — they cannot be exported or transferred',
              )}
            </li>
            <li>
              {t(
                'Data recovery is NOT possible if encryption keys are lost (e.g., clearing browser data)',
              )}
            </li>
            <li>
              {t(
                'We do not have access to your data or encryption keys — zero-knowledge architecture',
              )}
            </li>
            <li>{t('You are solely responsible for backing up your data')}</li>
          </ul>

          <h3>{t('Use at Your Own Risk')}</h3>
          <p>
            {t(
              'DEVS is provided "as is" without warranty of any kind. The software is experimental and:',
            )}
          </p>
          <ul>
            <li>{t('May contain bugs or errors')}</li>
            <li>{t('AI-generated content may be inaccurate')}</li>
            <li>
              {t('We are not responsible for any damages arising from use')}
            </li>
          </ul>

          <h3>{t('Your Responsibilities')}</h3>
          <p>{t('You are responsible for:')}</p>
          <ul>
            <li>{t('Your API keys and their associated costs')}</li>
            <li>{t('Content you generate using the platform')}</li>
            <li>{t('Compliance with LLM provider terms of service')}</li>
            <li>{t('Ensuring generated content meets your local laws')}</li>
          </ul>

          <h3>{t('External Connectors')}</h3>
          <p>
            {t(
              'When connecting external services (Gmail, Google Drive, Notion, etc.):',
            )}
          </p>
          <ul>
            <li>
              {t(
                'You authorize DEVS to access these services on your behalf via OAuth 2.0',
              )}
            </li>
            <li>
              {t(
                'OAuth tokens are encrypted and stored locally on your device',
              )}
            </li>
            <li>
              {t(
                'You can revoke access at any time via connector settings or the provider\u2019s dashboard',
              )}
            </li>
            <li>
              {t(
                'DEVS requests minimum necessary permissions (read-only where possible)',
              )}
            </li>
            <li>
              {t(
                'You remain responsible for data imported from external services',
              )}
            </li>
          </ul>

          <h3>{t('AI-Generated Content')}</h3>
          <p>{t('Content generated by AI agents:')}</p>
          <ul>
            <li>{t('Should be reviewed before use')}</li>
            <li>{t('May require fact-checking')}</li>
            <li>{t('Does not represent our views or opinions')}</li>
          </ul>

          <h3>{t('Open Source & Auditability')}</h3>
          <p>
            {t(
              'All DEVS source code is publicly available and auditable on GitHub. Security architecture and encryption implementations are documented and can be independently verified.',
            )}
          </p>

          <h3>{t('Changes')}</h3>
          <p>
            {t(
              'We may update these terms at any time. Continued use constitutes acceptance of changes.',
            )}
          </p>

          <h3>{t('Contact')}</h3>
          <p>
            {t('For questions, open an issue on our')}{' '}
            <a href="https://github.com/codename-co/devs">
              {t('GitHub repository')}
            </a>
            .
          </p>
        </Container>
      </Section>
    </Layout>
  )
}

const localI18n = {
  en: [
    'Terms of Service',
    'Usage terms and conditions',
    'Last updated: {date}',
    'By using DEVS, you agree to these terms.',
    'License',
    'DEVS is open-source software released under the',
    'MIT License',
    'You are free to use, modify, and distribute the software.',
    'Data & Security',
    'Your data is protected by browser-native encryption:',
    'All credentials and sensitive content are encrypted at rest with AES-GCM-256',
    'Encryption keys are non-extractable and device-bound \u2014 they cannot be exported or transferred',
    'Data recovery is NOT possible if encryption keys are lost (e.g., clearing browser data)',
    'We do not have access to your data or encryption keys \u2014 zero-knowledge architecture',
    'You are solely responsible for backing up your data',
    'Use at Your Own Risk',
    'DEVS is provided "as is" without warranty of any kind. The software is experimental and:',
    'May contain bugs or errors',
    'AI-generated content may be inaccurate',
    'We are not responsible for any damages arising from use',
    'Your Responsibilities',
    'You are responsible for:',
    'Your API keys and their associated costs',
    'Content you generate using the platform',
    'Compliance with LLM provider terms of service',
    'Ensuring generated content meets your local laws',
    'External Connectors',
    'When connecting external services (Gmail, Google Drive, Notion, etc.):',
    'You authorize DEVS to access these services on your behalf via OAuth 2.0',
    'OAuth tokens are encrypted and stored locally on your device',
    'You can revoke access at any time via connector settings or the provider\u2019s dashboard',
    'DEVS requests minimum necessary permissions (read-only where possible)',
    'You remain responsible for data imported from external services',
    'AI-Generated Content',
    'Content generated by AI agents:',
    'Should be reviewed before use',
    'May require fact-checking',
    'Does not represent our views or opinions',
    'Open Source & Auditability',
    'All DEVS source code is publicly available and auditable on GitHub. Security architecture and encryption implementations are documented and can be independently verified.',
    'Changes',
    'We may update these terms at any time. Continued use constitutes acceptance of changes.',
    'Contact',
    'For questions, open an issue on our',
    'GitHub repository',
  ] as const,
  ar: {
    'Terms of Service': 'شروط الخدمة',
    'Usage terms and conditions': 'شروط وأحكام الاستخدام',
    'Last updated: {date}': 'آخر تحديث: {date}',
    'By using DEVS, you agree to these terms.':
      'باستخدامك DEVS، فإنك توافق على هذه الشروط.',
    License: 'الترخيص',
    'DEVS is open-source software released under the':
      'DEVS هو برنامج مفتوح المصدر تم إصداره بموجب',
    'MIT License': 'رخصة MIT',
    'You are free to use, modify, and distribute the software.':
      'يحق لك استخدام البرنامج وتعديله وتوزيعه بحرية.',
    'Data & Security': 'البيانات والأمان',
    'Your data is protected by browser-native encryption:':
      'بياناتك محمية بالتشفير المدمج في المتصفح:',
    'All credentials and sensitive content are encrypted at rest with AES-GCM-256':
      'جميع بيانات الاعتماد والمحتوى الحساس مشفرة في حالة السكون باستخدام AES-GCM-256',
    'Encryption keys are non-extractable and device-bound \u2014 they cannot be exported or transferred':
      'مفاتيح التشفير غير قابلة للاستخراج ومرتبطة بالجهاز — لا يمكن تصديرها أو نقلها',
    'Data recovery is NOT possible if encryption keys are lost (e.g., clearing browser data)':
      'استرداد البيانات غير ممكن في حال فقدان مفاتيح التشفير (مثل مسح بيانات المتصفح)',
    'We do not have access to your data or encryption keys \u2014 zero-knowledge architecture':
      'ليس لدينا حق الوصول إلى بياناتك أو مفاتيح التشفير — بنية صفرية المعرفة',
    'You are solely responsible for backing up your data':
      'أنت المسؤول الوحيد عن النسخ الاحتياطي لبياناتك',
    'Use at Your Own Risk': 'الاستخدام على مسؤوليتك الخاصة',
    'DEVS is provided "as is" without warranty of any kind. The software is experimental and:':
      'يتم توفير DEVS "كما هو" دون أي ضمان من أي نوع. البرنامج تجريبي وقد:',
    'May contain bugs or errors': 'يحتوي على أخطاء أو مشاكل',
    'AI-generated content may be inaccurate':
      'قد يكون المحتوى الذي أنشأه الذكاء الاصطناعي غير دقيق',
    'We are not responsible for any damages arising from use':
      'لسنا مسؤولين عن أي أضرار ناتجة عن الاستخدام',
    'Your Responsibilities': 'مسؤولياتك',
    'You are responsible for:': 'أنت مسؤول عن:',
    'Your API keys and their associated costs':
      'مفاتيح API الخاصة بك وتكاليفها المرتبطة',
    'Content you generate using the platform':
      'المحتوى الذي تنشئه باستخدام المنصة',
    'Compliance with LLM provider terms of service': 'الامتثال لشروط مزودي LLM',
    'Ensuring generated content meets your local laws':
      'ضمان أن المحتوى المولد يلتزم بقوانينك المحلية',
    'External Connectors': 'الموصلات الخارجية',
    'When connecting external services (Gmail, Google Drive, Notion, etc.):':
      'عند ربط الخدمات الخارجية (Gmail، Google Drive، Notion، إلخ):',
    'You authorize DEVS to access these services on your behalf via OAuth 2.0':
      'أنت تفوض DEVS بالوصول إلى هذه الخدمات نيابة عنك عبر OAuth 2.0',
    'OAuth tokens are encrypted and stored locally on your device':
      'رموز OAuth مشفرة ومخزنة محليًا على جهازك',
    'You can revoke access at any time via connector settings or the provider\u2019s dashboard':
      'يمكنك إلغاء الوصول في أي وقت عبر إعدادات الموصل أو لوحة تحكم المزود',
    'DEVS requests minimum necessary permissions (read-only where possible)':
      'يطلب DEVS الحد الأدنى من الصلاحيات الضرورية (للقراءة فقط حيثما أمكن)',
    'You remain responsible for data imported from external services':
      'تبقى مسؤولاً عن البيانات المستوردة من الخدمات الخارجية',
    'AI-Generated Content': 'محتوى تم إنشاؤه بواسطة الذكاء الاصطناعي',
    'Content generated by AI agents:':
      'المحتوى الذي ينشئه وكلاء الذكاء الاصطناعي:',
    'Should be reviewed before use': 'يجب مراجعته قبل الاستخدام',
    'May require fact-checking': 'قد يتطلب التحقق من الحقائق',
    'Does not represent our views or opinions': 'لا يمثل وجهات نظرنا أو آرائنا',
    'Open Source & Auditability': 'المصدر المفتوح وقابلية التدقيق',
    'All DEVS source code is publicly available and auditable on GitHub. Security architecture and encryption implementations are documented and can be independently verified.':
      'جميع أكواد DEVS المصدرية متاحة للعامة وقابلة للتدقيق على GitHub. بنية الأمان وتطبيقات التشفير موثقة ويمكن التحقق منها بشكل مستقل.',
    Changes: 'التغييرات',
    'We may update these terms at any time. Continued use constitutes acceptance of changes.':
      'قد نقوم بتحديث هذه الشروط في أي وقت. استمرار الاستخدام يعني قبول التغييرات.',
    Contact: 'اتصل',
    'For questions, open an issue on our': 'للاستفسارات، افتح تذكرة في',
    'GitHub repository': 'مستودع GitHub',
  },
  de: {
    'Terms of Service': 'Nutzungsbedingungen',
    'Usage terms and conditions': 'Nutzungsbedingungen und Konditionen',
    'Last updated: {date}': 'Zuletzt aktualisiert: {date}',
    'By using DEVS, you agree to these terms.':
      'Durch die Nutzung von DEVS stimmen Sie diesen Bedingungen zu.',
    License: 'Lizenz',
    'DEVS is open-source software released under the':
      'DEVS ist Open-Source-Software, veröffentlicht unter der',
    'MIT License': 'MIT-Lizenz',
    'You are free to use, modify, and distribute the software.':
      'Sie dürfen die Software frei verwenden, modifizieren und weitergeben.',
    'Data & Security': 'Daten & Sicherheit',
    'Your data is protected by browser-native encryption:':
      'Ihre Daten sind durch browsereigene Verschlüsselung geschützt:',
    'All credentials and sensitive content are encrypted at rest with AES-GCM-256':
      'Alle Zugangsdaten und sensiblen Inhalte werden im Ruhezustand mit AES-GCM-256 verschlüsselt',
    'Encryption keys are non-extractable and device-bound \u2014 they cannot be exported or transferred':
      'Verschlüsselungsschlüssel sind nicht extrahierbar und gerätegebunden — sie können weder exportiert noch übertragen werden',
    'Data recovery is NOT possible if encryption keys are lost (e.g., clearing browser data)':
      'Eine Datenwiederherstellung ist NICHT möglich, wenn Verschlüsselungsschlüssel verloren gehen (z. B. durch Löschen der Browserdaten)',
    'We do not have access to your data or encryption keys \u2014 zero-knowledge architecture':
      'Wir haben keinen Zugriff auf Ihre Daten oder Verschlüsselungsschlüssel — Zero-Knowledge-Architektur',
    'You are solely responsible for backing up your data':
      'Sie sind allein für die Sicherung Ihrer Daten verantwortlich',
    'Use at Your Own Risk': 'Nutzung auf eigene Gefahr',
    'DEVS is provided "as is" without warranty of any kind. The software is experimental and:':
      'DEVS wird ohne jegliche Gewährleistung bereitgestellt. Die Software ist experimentell und:',
    'May contain bugs or errors': 'Kann Fehler oder Bugs enthalten',
    'AI-generated content may be inaccurate':
      'KI-generierte Inhalte können ungenau sein',
    'We are not responsible for any damages arising from use':
      'Wir übernehmen keine Haftung für Schäden aus der Nutzung',
    'Your Responsibilities': 'Ihre Verantwortlichkeiten',
    'You are responsible for:': 'Sie sind verantwortlich für:',
    'Your API keys and their associated costs':
      'Ihre API-Schlüssel und die damit verbundenen Kosten',
    'Content you generate using the platform':
      'Inhalte, die Sie mit der Plattform generieren',
    'Compliance with LLM provider terms of service':
      'Einhaltung der Bedingungen der LLM-Anbieter',
    'Ensuring generated content meets your local laws':
      'Sicherstellung, dass generierte Inhalte Ihren lokalen Gesetzen entsprechen',
    'External Connectors': 'Externe Konnektoren',
    'When connecting external services (Gmail, Google Drive, Notion, etc.):':
      'Beim Verbinden externer Dienste (Gmail, Google Drive, Notion usw.):',
    'You authorize DEVS to access these services on your behalf via OAuth 2.0':
      'Sie autorisieren DEVS, über OAuth 2.0 in Ihrem Namen auf diese Dienste zuzugreifen',
    'OAuth tokens are encrypted and stored locally on your device':
      'OAuth-Tokens werden verschlüsselt und lokal auf Ihrem Gerät gespeichert',
    'You can revoke access at any time via connector settings or the provider\u2019s dashboard':
      'Sie können den Zugriff jederzeit über die Konnektoreinstellungen oder das Dashboard des Anbieters widerrufen',
    'DEVS requests minimum necessary permissions (read-only where possible)':
      'DEVS fordert nur die minimal notwendigen Berechtigungen an (schreibgeschützt, wo möglich)',
    'You remain responsible for data imported from external services':
      'Sie bleiben für aus externen Diensten importierte Daten verantwortlich',
    'AI-Generated Content': 'KI-generierte Inhalte',
    'Content generated by AI agents:': 'Von KI-Agenten generierte Inhalte:',
    'Should be reviewed before use': 'Sollten vor der Nutzung überprüft werden',
    'May require fact-checking': 'Kann Faktenüberprüfung erfordern',
    'Does not represent our views or opinions':
      'Stellt nicht unsere Ansichten oder Meinungen dar',
    'Open Source & Auditability': 'Open Source & Überprüfbarkeit',
    'All DEVS source code is publicly available and auditable on GitHub. Security architecture and encryption implementations are documented and can be independently verified.':
      'Der gesamte DEVS-Quellcode ist öffentlich verfügbar und auf GitHub überprüfbar. Die Sicherheitsarchitektur und Verschlüsselungsimplementierungen sind dokumentiert und können unabhängig verifiziert werden.',
    Changes: 'Änderungen',
    'We may update these terms at any time. Continued use constitutes acceptance of changes.':
      'Wir können diese Bedingungen jederzeit aktualisieren. Die fortgesetzte Nutzung gilt als Zustimmung zu den Änderungen.',
    Contact: 'Kontakt',
    'For questions, open an issue on our':
      'Bei Fragen öffnen Sie bitte ein Issue in unserem',
    'GitHub repository': 'GitHub-Repository',
  },
  es: {
    'Terms of Service': 'Términos de servicio',
    'Usage terms and conditions': 'Términos y condiciones de uso',
    'Last updated: {date}': 'Última actualización: {date}',
    'By using DEVS, you agree to these terms.':
      'Al usar DEVS, aceptas estos términos.',
    License: 'Licencia',
    'DEVS is open-source software released under the':
      'DEVS es software de código abierto publicado bajo la',
    'MIT License': 'Licencia MIT',
    'You are free to use, modify, and distribute the software.':
      'Eres libre de usar, modificar y distribuir el software.',
    'Data & Security': 'Datos y seguridad',
    'Your data is protected by browser-native encryption:':
      'Tus datos están protegidos por cifrado nativo del navegador:',
    'All credentials and sensitive content are encrypted at rest with AES-GCM-256':
      'Todas las credenciales y contenido sensible se cifran en reposo con AES-GCM-256',
    'Encryption keys are non-extractable and device-bound \u2014 they cannot be exported or transferred':
      'Las claves de cifrado no son extraíbles y están vinculadas al dispositivo — no pueden exportarse ni transferirse',
    'Data recovery is NOT possible if encryption keys are lost (e.g., clearing browser data)':
      'La recuperación de datos NO es posible si se pierden las claves de cifrado (por ejemplo, al borrar datos del navegador)',
    'We do not have access to your data or encryption keys \u2014 zero-knowledge architecture':
      'No tenemos acceso a tus datos ni a tus claves de cifrado — arquitectura de conocimiento cero',
    'You are solely responsible for backing up your data':
      'Eres el único responsable de realizar copias de seguridad de tus datos',
    'Use at Your Own Risk': 'Uso bajo tu propio riesgo',
    'DEVS is provided "as is" without warranty of any kind. The software is experimental and:':
      'DEVS se proporciona "tal cual" sin garantía de ningún tipo. El software es experimental y:',
    'May contain bugs or errors': 'Puede contener errores o fallos',
    'AI-generated content may be inaccurate':
      'El contenido generado por IA puede ser inexacto',
    'We are not responsible for any damages arising from use':
      'No somos responsables de los daños derivados del uso',
    'Your Responsibilities': 'Tus responsabilidades',
    'You are responsible for:': 'Eres responsable de:',
    'Your API keys and their associated costs':
      'Tus claves API y sus costes asociados',
    'Content you generate using the platform':
      'El contenido que generes usando la plataforma',
    'Compliance with LLM provider terms of service':
      'Cumplimiento de los términos de los proveedores LLM',
    'Ensuring generated content meets your local laws':
      'Asegurarte de que el contenido generado cumpla tus leyes locales',
    'External Connectors': 'Conectores externos',
    'When connecting external services (Gmail, Google Drive, Notion, etc.):':
      'Al conectar servicios externos (Gmail, Google Drive, Notion, etc.):',
    'You authorize DEVS to access these services on your behalf via OAuth 2.0':
      'Autorizas a DEVS a acceder a estos servicios en tu nombre mediante OAuth 2.0',
    'OAuth tokens are encrypted and stored locally on your device':
      'Los tokens OAuth se cifran y almacenan localmente en tu dispositivo',
    'You can revoke access at any time via connector settings or the provider\u2019s dashboard':
      'Puedes revocar el acceso en cualquier momento desde la configuración del conector o el panel del proveedor',
    'DEVS requests minimum necessary permissions (read-only where possible)':
      'DEVS solicita los permisos mínimos necesarios (solo lectura cuando sea posible)',
    'You remain responsible for data imported from external services':
      'Sigues siendo responsable de los datos importados desde servicios externos',
    'AI-Generated Content': 'Contenido generado por IA',
    'Content generated by AI agents:': 'El contenido generado por agentes IA:',
    'Should be reviewed before use': 'Debe revisarse antes de usar',
    'May require fact-checking': 'Puede requerir verificación de hechos',
    'Does not represent our views or opinions':
      'No representa nuestras opiniones o puntos de vista',
    'Open Source & Auditability': 'Código abierto y auditabilidad',
    'All DEVS source code is publicly available and auditable on GitHub. Security architecture and encryption implementations are documented and can be independently verified.':
      'Todo el código fuente de DEVS está disponible públicamente y es auditable en GitHub. La arquitectura de seguridad y las implementaciones de cifrado están documentadas y pueden verificarse de forma independiente.',
    Changes: 'Cambios',
    'We may update these terms at any time. Continued use constitutes acceptance of changes.':
      'Podemos actualizar estos términos en cualquier momento. El uso continuado constituye aceptación de los cambios.',
    Contact: 'Contacto',
    'For questions, open an issue on our':
      'Para preguntas, abre un issue en nuestro',
    'GitHub repository': 'repositorio de GitHub',
  },
  fr: {
    'Terms of Service': "Conditions d'utilisation",
    'Usage terms and conditions': "Termes et conditions d'utilisation",
    'Last updated: {date}': 'Dernière mise à jour : {date}',
    'By using DEVS, you agree to these terms.':
      'En utilisant DEVS, vous acceptez ces conditions.',
    License: 'Licence',
    'DEVS is open-source software released under the':
      'DEVS est un logiciel open-source publié sous',
    'MIT License': 'Licence MIT',
    'You are free to use, modify, and distribute the software.':
      "Vous êtes libre d'utiliser, modifier et distribuer le logiciel.",
    'Data & Security': 'Données et sécurité',
    'Your data is protected by browser-native encryption:':
      'Vos données sont protégées par le chiffrement natif du navigateur :',
    'All credentials and sensitive content are encrypted at rest with AES-GCM-256':
      'Toutes les informations d\u2019identification et le contenu sensible sont chiffrés au repos avec AES-GCM-256',
    'Encryption keys are non-extractable and device-bound \u2014 they cannot be exported or transferred':
      'Les clés de chiffrement sont non extractibles et liées à l\u2019appareil — elles ne peuvent être ni exportées ni transférées',
    'Data recovery is NOT possible if encryption keys are lost (e.g., clearing browser data)':
      'La récupération des données N\u2019EST PAS possible si les clés de chiffrement sont perdues (par ex., en effaçant les données du navigateur)',
    'We do not have access to your data or encryption keys \u2014 zero-knowledge architecture':
      'Nous n\u2019avons pas accès à vos données ni à vos clés de chiffrement — architecture à connaissance nulle',
    'You are solely responsible for backing up your data':
      'Vous êtes seul responsable de la sauvegarde de vos données',
    'Use at Your Own Risk': 'Utilisation à vos risques',
    'DEVS is provided "as is" without warranty of any kind. The software is experimental and:':
      'DEVS est fourni "tel quel" sans aucune garantie. Le logiciel est expérimental et :',
    'May contain bugs or errors': 'Peut contenir des bugs ou erreurs',
    'AI-generated content may be inaccurate':
      "Le contenu généré par l'IA peut être inexact",
    'We are not responsible for any damages arising from use':
      "Nous ne sommes pas responsables des dommages résultant de l'utilisation",
    'Your Responsibilities': 'Vos responsabilités',
    'You are responsible for:': 'Vous êtes responsable de :',
    'Your API keys and their associated costs':
      'Vos clés API et leurs coûts associés',
    'Content you generate using the platform':
      'Le contenu que vous générez avec la plateforme',
    'Compliance with LLM provider terms of service':
      'La conformité avec les conditions des fournisseurs LLM',
    'Ensuring generated content meets your local laws':
      "S'assurer que le contenu généré respecte vos lois locales",
    'External Connectors': 'Connecteurs externes',
    'When connecting external services (Gmail, Google Drive, Notion, etc.):':
      'Lors de la connexion de services externes (Gmail, Google Drive, Notion, etc.) :',
    'You authorize DEVS to access these services on your behalf via OAuth 2.0':
      'Vous autorisez DEVS à accéder à ces services en votre nom via OAuth 2.0',
    'OAuth tokens are encrypted and stored locally on your device':
      'Les jetons OAuth sont chiffrés et stockés localement sur votre appareil',
    'You can revoke access at any time via connector settings or the provider\u2019s dashboard':
      'Vous pouvez révoquer l\u2019accès à tout moment via les paramètres du connecteur ou le tableau de bord du fournisseur',
    'DEVS requests minimum necessary permissions (read-only where possible)':
      'DEVS demande les permissions minimales nécessaires (lecture seule lorsque possible)',
    'You remain responsible for data imported from external services':
      'Vous restez responsable des données importées depuis les services externes',
    'AI-Generated Content': "Contenu généré par l'IA",
    'Content generated by AI agents:': 'Le contenu généré par les agents IA :',
    'Should be reviewed before use': 'Doit être vérifié avant utilisation',
    'May require fact-checking': 'Peut nécessiter une vérification des faits',
    'Does not represent our views or opinions':
      'Ne représente pas nos points de vue ou opinions',
    'Open Source & Auditability': 'Open source et auditabilité',
    'All DEVS source code is publicly available and auditable on GitHub. Security architecture and encryption implementations are documented and can be independently verified.':
      'L\u2019intégralité du code source de DEVS est publiquement disponible et auditable sur GitHub. L\u2019architecture de sécurité et les implémentations de chiffrement sont documentées et peuvent être vérifiées de manière indépendante.',
    Changes: 'Modifications',
    'We may update these terms at any time. Continued use constitutes acceptance of changes.':
      "Nous pouvons mettre à jour ces conditions à tout moment. L'utilisation continue constitue une acceptation des modifications.",
    Contact: 'Contact',
    'For questions, open an issue on our':
      'Pour toute question, ouvrez une issue sur notre',
    'GitHub repository': 'dépôt GitHub',
  },
  ko: {
    'Terms of Service': '이용 약관',
    'Usage terms and conditions': '이용 조건 및 약관',
    'Last updated: {date}': '최종 업데이트: {date}',
    'By using DEVS, you agree to these terms.':
      'DEVS를 사용함으로써 귀하는 본 약관에 동의하게 됩니다.',
    License: '라이선스',
    'DEVS is open-source software released under the':
      'DEVS는 오픈소스 소프트웨어로 다음 라이선스 하에 배포됩니다:',
    'MIT License': 'MIT 라이선스',
    'You are free to use, modify, and distribute the software.':
      '소프트웨어를 자유롭게 사용, 수정, 배포할 수 있습니다.',
    'Data & Security': '데이터 및 보안',
    'Your data is protected by browser-native encryption:':
      '귀하의 데이터는 브라우저 네이티브 암호화로 보호됩니다:',
    'All credentials and sensitive content are encrypted at rest with AES-GCM-256':
      '모든 자격 증명 및 민감한 콘텐츠는 AES-GCM-256으로 저장 시 암호화됩니다',
    'Encryption keys are non-extractable and device-bound \u2014 they cannot be exported or transferred':
      '암호화 키는 추출 불가능하며 기기에 귀속됩니다 — 내보내거나 전송할 수 없습니다',
    'Data recovery is NOT possible if encryption keys are lost (e.g., clearing browser data)':
      '암호화 키를 분실하면 데이터 복구가 불가능합니다 (예: 브라우저 데이터 삭제)',
    'We do not have access to your data or encryption keys \u2014 zero-knowledge architecture':
      '당사는 귀하의 데이터나 암호화 키에 접근할 수 없습니다 — 제로 지식 아키텍처',
    'You are solely responsible for backing up your data':
      '데이터 백업에 대한 책임은 전적으로 귀하에게 있습니다',
    'Use at Your Own Risk': '본인 책임하에 사용',
    'DEVS is provided "as is" without warranty of any kind. The software is experimental and:':
      'DEVS는 어떠한 보증도 없이 "있는 그대로" 제공됩니다. 소프트웨어는 실험적이며:',
    'May contain bugs or errors': '버그 또는 오류가 있을 수 있음',
    'AI-generated content may be inaccurate':
      'AI가 생성한 내용이 부정확할 수 있음',
    'We are not responsible for any damages arising from use':
      '사용으로 인한 손해에 대해 책임지지 않습니다',
    'Your Responsibilities': '귀하의 책임',
    'You are responsible for:': '귀하는 다음에 대해 책임이 있습니다:',
    'Your API keys and their associated costs': '귀하의 API 키 및 관련 비용',
    'Content you generate using the platform': '플랫폼을 통해 생성한 콘텐츠',
    'Compliance with LLM provider terms of service': 'LLM 공급자 약관 준수',
    'Ensuring generated content meets your local laws':
      '생성된 콘텐츠가 귀하의 현지 법률을 준수하는지 확인',
    'External Connectors': '외부 커넥터',
    'When connecting external services (Gmail, Google Drive, Notion, etc.):':
      '외부 서비스(Gmail, Google Drive, Notion 등)를 연결할 때:',
    'You authorize DEVS to access these services on your behalf via OAuth 2.0':
      '귀하는 OAuth 2.0을 통해 DEVS가 귀하를 대신하여 이러한 서비스에 접근하도록 승인합니다',
    'OAuth tokens are encrypted and stored locally on your device':
      'OAuth 토큰은 암호화되어 귀하의 기기에 로컬로 저장됩니다',
    'You can revoke access at any time via connector settings or the provider\u2019s dashboard':
      '커넥터 설정 또는 제공업체의 대시보드에서 언제든지 접근 권한을 취소할 수 있습니다',
    'DEVS requests minimum necessary permissions (read-only where possible)':
      'DEVS는 필요한 최소한의 권한만 요청합니다 (가능한 경우 읽기 전용)',
    'You remain responsible for data imported from external services':
      '외부 서비스에서 가져온 데이터에 대한 책임은 귀하에게 있습니다',
    'AI-Generated Content': 'AI 생성 콘텐츠',
    'Content generated by AI agents:': 'AI 에이전트가 생성한 콘텐츠:',
    'Should be reviewed before use': '사용 전 반드시 검토해야 함',
    'May require fact-checking': '사실 확인이 필요할 수 있음',
    'Does not represent our views or opinions':
      '당사의 견해나 의견을 대변하지 않음',
    'Open Source & Auditability': '오픈소스 및 감사 가능성',
    'All DEVS source code is publicly available and auditable on GitHub. Security architecture and encryption implementations are documented and can be independently verified.':
      '모든 DEVS 소스 코드는 GitHub에서 공개적으로 이용 가능하며 감사할 수 있습니다. 보안 아키텍처와 암호화 구현은 문서화되어 있으며 독립적으로 검증할 수 있습니다.',
    Changes: '변경사항',
    'We may update these terms at any time. Continued use constitutes acceptance of changes.':
      '본 약관은 언제든지 변경될 수 있으며, 계속 사용 시 변경에 동의하는 것으로 간주됩니다.',
    Contact: '문의',
    'For questions, open an issue on our':
      '문의사항은 다음에서 이슈를 등록하세요:',
    'GitHub repository': 'GitHub 저장소',
  },
}
