import { en } from './en'

type I18n = Record<(typeof en)[number], string>

export const ar: I18n = {
  Library: 'المكتبة',
  'All deliverables generated by your agents':
    'جميع المخرجات التي أنتجها وكلاؤك',
  'Loading library…': 'جارٍ تحميل المكتبة…',
  'No items yet': 'لا توجد عناصر بعد',
  'Items will appear here once agents produce deliverables.':
    'ستظهر العناصر هنا بمجرد أن ينتج الوكلاء مخرجات.',
  All: 'الكل',
  draft: 'مسودة',
  review: 'مراجعة',
  approved: 'معتمد',
  rejected: 'مرفوض',
  final: 'نهائي',
  document: 'مستند',
  code: 'كود',
  design: 'تصميم',
  analysis: 'تحليل',
  plan: 'خطة',
  report: 'تقرير',
  'Filter by status': 'تصفية حسب الحالة',
  'No {status} items found': 'لم يتم العثور على عناصر {status}',
  'v{version}': 'v{version}',
  Close: 'إغلاق',
  Download: 'تنزيل',
}
