import { en } from './en'

type I18n = Record<(typeof en)[number], string>

/** Unreviewed machine-translation draft: bn. Needs native review. */
export const bn: I18n = {
  'Library': 'লাইব্রেরি',
  'All deliverables generated by your agents': 'আপনার এজেন্টদের দ্বারা উত্পন্ন সমস্ত বিতরণযোগ্য',
  'Loading library…': 'লাইব্রেরি লোড হচ্ছে...',
  'No items yet': 'এখনও কোন আইটেম',
  'Items will appear here once agents produce deliverables.': 'এজেন্ট ডেলিভারিযোগ্য পণ্যগুলি তৈরি করলে আইটেমগুলি এখানে প্রদর্শিত হবে।',
  'All': 'সব',
  'draft': 'খসড়া',
  'review': 'পর্যালোচনা',
  'approved': 'অনুমোদিত',
  'rejected': 'প্রত্যাখ্যাত',
  'final': 'চূড়ান্ত',
  'document': 'নথি',
  'code': 'কোড',
  'design': 'নকশা',
  'analysis': 'বিশ্লেষণ',
  'plan': 'পরিকল্পনা',
  'report': 'রিপোর্ট',
  'Filter by status': 'স্থিতি দ্বারা ফিল্টার করুন',
  'No {status} items found': 'কোনো {status} আইটেম পাওয়া যায়নি',
  'v{version}': 'v{version}',
  'Close': 'বন্ধ',
  'Download': 'ডাউনলোড করুন',
} as const
