import { en } from './en'

type I18n = Record<(typeof en)[number], string>

/** Unreviewed machine-translation draft: ceb. Needs native review. */
export const ceb: I18n = {
  'Library': 'Library',
  'All deliverables generated by your agents': 'Ang tanan nga mga paghatud nga gihimo sa imong mga ahente',
  'Loading library…': 'Nagkarga sa librarya…',
  'No items yet': 'Wala pa\'y mga butang',
  'Items will appear here once agents produce deliverables.': 'Ang mga butang makita dinhi sa higayon nga ang mga ahente makahimo og mga deliverable.',
  'All': 'Tanan',
  'draft': 'draft',
  'review': 'pagrepaso',
  'approved': 'giaprobahan',
  'rejected': 'gisalikway',
  'final': 'katapusan',
  'document': 'dokumento',
  'code': 'kodigo',
  'design': 'disenyo',
  'analysis': 'pagtuki',
  'plan': 'plano',
  'report': 'report',
  'Filter by status': 'Pagsala pinaagi sa kahimtang',
  'No {status} items found': 'Walay {status} nga mga butang nga nakit-an',
  'v{version}': 'v{version}',
  'Close': 'Duol',
  'Download': 'Pag-download',
} as const
