import { en } from './en'

type I18n = Record<(typeof en)[number], string>

export const de: I18n = {
  Library: 'Bibliothek',
  'All deliverables generated by your agents':
    'Alle von Ihren Agenten erstellten Ergebnisse',
  'Loading library…': 'Bibliothek wird geladen…',
  'No items yet': 'Noch keine Einträge',
  'Items will appear here once agents produce deliverables.':
    'Einträge erscheinen hier, sobald Agenten Ergebnisse erstellen.',
  All: 'Alle',
  draft: 'Entwurf',
  review: 'Überprüfung',
  approved: 'Genehmigt',
  rejected: 'Abgelehnt',
  final: 'Final',
  document: 'Dokument',
  code: 'Code',
  design: 'Design',
  analysis: 'Analyse',
  plan: 'Plan',
  report: 'Bericht',
  'Filter by status': 'Nach Status filtern',
  'No {status} items found': 'Keine {status} Einträge gefunden',
  'v{version}': 'v{version}',
  Close: 'Schließen',
  Download: 'Herunterladen',
}
