import { en } from './en'

type I18n = Record<(typeof en)[number], string>

export const es: I18n = {
  Library: 'Biblioteca',
  'All deliverables generated by your agents':
    'Todos los entregables generados por tus agentes',
  'Loading library…': 'Cargando biblioteca…',
  'No items yet': 'Aún no hay elementos',
  'Items will appear here once agents produce deliverables.':
    'Los elementos aparecerán aquí una vez que los agentes produzcan entregables.',
  All: 'Todos',
  draft: 'borrador',
  review: 'revisión',
  approved: 'aprobado',
  rejected: 'rechazado',
  final: 'final',
  document: 'documento',
  code: 'código',
  design: 'diseño',
  analysis: 'análisis',
  plan: 'plan',
  report: 'informe',
  'Filter by status': 'Filtrar por estado',
  'No {status} items found': 'No se encontraron elementos {status}',
  'v{version}': 'v{version}',
  Close: 'Cerrar',
  Download: 'Descargar',
}
