import { en } from './en'

type I18n = Record<(typeof en)[number], string>

/** Unreviewed machine-translation draft: fil. Needs native review. */
export const fil: I18n = {
  'Library': 'Aklatan',
  'All deliverables generated by your agents': 'Lahat ng mga deliverable na nabuo ng iyong mga ahente',
  'Loading library…': 'Nilo-load ang library…',
  'No items yet': 'Wala pang mga item',
  'Items will appear here once agents produce deliverables.': 'Lalabas dito ang mga item kapag gumawa ang mga ahente ng mga deliverable.',
  'All': 'Lahat',
  'draft': 'burador',
  'review': 'pagsusuri',
  'approved': 'naaprubahan',
  'rejected': 'tinanggihan',
  'final': 'pangwakas',
  'document': 'dokumento',
  'code': 'code',
  'design': 'disenyo',
  'analysis': 'pagsusuri',
  'plan': 'plano',
  'report': 'ulat',
  'Filter by status': 'I-filter ayon sa katayuan',
  'No {status} items found': 'Walang nakitang {status} na item',
  'v{version}': 'v{version}',
  'Close': 'Isara',
  'Download': 'I-download',
} as const
