import { en } from './en'

type I18n = Record<(typeof en)[number], string>

export const fr: I18n = {
  Library: 'Bibliothèque',
  'All deliverables generated by your agents':
    'Tous les livrables générés par vos agents',
  'Loading library…': 'Chargement de la bibliothèque…',
  'No items yet': 'Aucun élément pour le moment',
  'Items will appear here once agents produce deliverables.':
    'Les éléments apparaîtront ici une fois que les agents auront produit des livrables.',
  All: 'Tous',
  draft: 'brouillon',
  review: 'révision',
  approved: 'approuvé',
  rejected: 'rejeté',
  final: 'final',
  document: 'document',
  code: 'code',
  design: 'design',
  analysis: 'analyse',
  plan: 'plan',
  report: 'rapport',
  'Filter by status': 'Filtrer par statut',
  'No {status} items found': 'Aucun élément {status} trouvé',
  'v{version}': 'v{version}',
  Close: 'Fermer',
  Download: 'Télécharger',
}
