import { en } from './en'

type I18n = Record<(typeof en)[number], string>

/** Unreviewed machine-translation draft: hi. Needs native review. */
export const hi: I18n = {
  'Library': 'पुस्तकालय',
  'All deliverables generated by your agents': 'आपके एजेंटों द्वारा उत्पन्न सभी डिलिवरेबल्स',
  'Loading library…': 'लाइब्रेरी लोड हो रही है...',
  'No items yet': 'अभी तक कोई आइटम नहीं',
  'Items will appear here once agents produce deliverables.': 'एजेंट द्वारा डिलिवरेबल्स तैयार करने के बाद आइटम यहां दिखाई देंगे।',
  'All': 'सब',
  'draft': 'ड्राफ्ट',
  'review': 'समीक्षा',
  'approved': 'स्वीकृत',
  'rejected': 'अस्वीकृत',
  'final': 'अंतिम',
  'document': 'दस्तावेज़',
  'code': 'कोड',
  'design': 'डिज़ाइन',
  'analysis': 'विश्लेषण',
  'plan': 'योजना',
  'report': 'रिपोर्ट',
  'Filter by status': 'स्थिति के अनुसार फ़िल्टर करें',
  'No {status} items found': 'कोई {status} आइटम नहीं मिला',
  'v{version}': 'v{version}',
  'Close': 'बंद करें',
  'Download': 'डाउनलोड करें',
} as const
