import { en } from './en'

type I18n = Record<(typeof en)[number], string>

/** Unreviewed machine-translation draft: id. Needs native review. */
export const id: I18n = {
  'Library': 'Perpustakaan',
  'All deliverables generated by your agents': 'Semua kiriman yang dihasilkan oleh agen Anda',
  'Loading library…': 'Memuat pustaka…',
  'No items yet': 'Belum ada item',
  'Items will appear here once agents produce deliverables.': 'Item akan muncul di sini setelah agen menghasilkan kiriman.',
  'All': 'Semua',
  'draft': 'konsep',
  'review': 'ulasan',
  'approved': 'disetujui',
  'rejected': 'ditolak',
  'final': 'terakhir',
  'document': 'dokumen',
  'code': 'kode',
  'design': 'desain',
  'analysis': 'analisis',
  'plan': 'rencana',
  'report': 'laporan',
  'Filter by status': 'Saring berdasarkan status',
  'No {status} items found': 'Tidak ada item {status} yang ditemukan',
  'v{version}': 'v{version}',
  'Close': 'Tutup',
  'Download': 'Unduh',
} as const
