import { en } from './en'

type I18n = Record<(typeof en)[number], string>

/** Unreviewed machine-translation draft: ja. Needs native review. */
export const ja: I18n = {
  'Library': '図書館',
  'All deliverables generated by your agents': 'エージェントによって生成されたすべての成果物',
  'Loading library…': 'ライブラリを読み込み中…',
  'No items yet': 'まだアイテムがありません',
  'Items will appear here once agents produce deliverables.': 'エージェントが成果物を作成すると、項目がここに表示されます。',
  'All': 'すべて',
  'draft': 'ドラフト',
  'review': 'レビュー',
  'approved': '承認された',
  'rejected': '拒否されました',
  'final': '最終的な',
  'document': '文書',
  'code': 'コード',
  'design': 'デザイン',
  'analysis': '分析',
  'plan': '計画',
  'report': '報告書',
  'Filter by status': 'ステータスでフィルタリングする',
  'No {status} items found': '{status} 項目が見つかりませんでした',
  'v{version}': 'v{version}',
  'Close': '閉じる',
  'Download': 'ダウンロード',
} as const
