import { en } from './en'

type I18n = Record<(typeof en)[number], string>

/** Unreviewed machine-translation draft: jv. Needs native review. */
export const jv: I18n = {
  'Library': 'Pustaka',
  'All deliverables generated by your agents': 'Kabeh kiriman sing digawe dening agen sampeyan',
  'Loading library…': 'Ngunggah perpustakaan…',
  'No items yet': 'Durung ana barang',
  'Items will appear here once agents produce deliverables.': 'Item bakal katon ing kene yen agen ngasilake kiriman.',
  'All': 'Kabeh',
  'draft': 'konsep',
  'review': 'review',
  'approved': 'disetujoni',
  'rejected': 'ditolak',
  'final': 'pungkasan',
  'document': 'dokumen',
  'code': 'kode',
  'design': 'desain',
  'analysis': 'analisis',
  'plan': 'rencana',
  'report': 'laporan',
  'Filter by status': 'Filter miturut status',
  'No {status} items found': 'Ora ana barang {status} sing ditemokake',
  'v{version}': 'v{version}',
  'Close': 'Nutup',
  'Download': 'Ngundhuh',
} as const
