import { en } from './en'

type I18n = Record<(typeof en)[number], string>

/** Unreviewed machine-translation draft: km. Needs native review. */
export const km: I18n = {
  'Library': 'បណ្ណាល័យ',
  'All deliverables generated by your agents': 'ការចែកចាយទាំងអស់ដែលបង្កើតដោយភ្នាក់ងាររបស់អ្នក។',
  'Loading library…': 'កំពុងផ្ទុកបណ្ណាល័យ...',
  'No items yet': 'មិនមានធាតុនៅឡើយទេ',
  'Items will appear here once agents produce deliverables.': 'ទំនិញនឹងបង្ហាញនៅទីនេះ នៅពេលដែលភ្នាក់ងារផលិតទំនិញដែលអាចចែកចាយបាន។',
  'All': 'ទាំងអស់។',
  'draft': 'សេចក្តីព្រាង',
  'review': 'ពិនិត្យ',
  'approved': 'អនុម័ត',
  'rejected': 'ច្រានចោល',
  'final': 'ចុងក្រោយ',
  'document': 'ឯកសារ',
  'code': 'កូដ',
  'design': 'ការរចនា',
  'analysis': 'ការវិភាគ',
  'plan': 'ផែនការ',
  'report': 'របាយការណ៍',
  'Filter by status': 'ត្រងតាមស្ថានភាព',
  'No {status} items found': 'រកមិនឃើញធាតុ {status} ទេ។',
  'v{version}': 'v{version}',
  'Close': 'បិទ',
  'Download': 'ទាញយក',
} as const
