import { en } from './en'

type I18n = Record<(typeof en)[number], string>

export const ko: I18n = {
  Library: '라이브러리',
  'All deliverables generated by your agents': '에이전트가 생성한 모든 산출물',
  'Loading library…': '라이브러리 로딩 중…',
  'No items yet': '아직 항목이 없습니다',
  'Items will appear here once agents produce deliverables.':
    '에이전트가 산출물을 생성하면 여기에 표시됩니다.',
  All: '전체',
  draft: '초안',
  review: '검토',
  approved: '승인',
  rejected: '거부',
  final: '최종',
  document: '문서',
  code: '코드',
  design: '디자인',
  analysis: '분석',
  plan: '계획',
  report: '보고서',
  'Filter by status': '상태별 필터',
  'No {status} items found': '{status} 항목을 찾을 수 없습니다',
  'v{version}': 'v{version}',
  Close: '닫기',
  Download: '다운로드',
}
