import { en } from './en'

type I18n = Record<(typeof en)[number], string>

/** Unreviewed machine-translation draft: lo. Needs native review. */
export const lo: I18n = {
  'Library': 'ຫໍສະໝຸດ',
  'All deliverables generated by your agents': 'ການຈັດສົ່ງທັງໝົດທີ່ສ້າງຂຶ້ນໂດຍຕົວແທນຂອງທ່ານ',
  'Loading library…': 'ກຳລັງໂຫຼດຫ້ອງສະໝຸດ...',
  'No items yet': 'ບໍ່ມີລາຍການເທື່ອ',
  'Items will appear here once agents produce deliverables.': 'ລາຍການຈະປາກົດຢູ່ທີ່ນີ້ເມື່ອຕົວແທນຜະລິດການຈັດສົ່ງ.',
  'All': 'ທັງໝົດ',
  'draft': 'ຮ່າງ',
  'review': 'ທົບທວນ',
  'approved': 'ອະນຸມັດ',
  'rejected': 'ປະຕິເສດ',
  'final': 'ສຸດທ້າຍ',
  'document': 'ເອກະສານ',
  'code': 'ລະຫັດ',
  'design': 'ການອອກແບບ',
  'analysis': 'ການວິເຄາະ',
  'plan': 'ແຜນການ',
  'report': 'ລາຍງານ',
  'Filter by status': 'ກັ່ນຕອງຕາມສະຖານະ',
  'No {status} items found': 'ບໍ່ພົບລາຍການ {status}',
  'v{version}': 'v{version}',
  'Close': 'ປິດ',
  'Download': 'ດາວໂຫຼດ',
} as const
