import { en } from './en'

type I18n = Record<(typeof en)[number], string>

/** Unreviewed machine-translation draft: ms. Needs native review. */
export const ms: I18n = {
  'Library': 'Perpustakaan',
  'All deliverables generated by your agents': 'Semua penghantaran yang dijana oleh ejen anda',
  'Loading library…': 'Memuatkan perpustakaan…',
  'No items yet': 'Tiada item lagi',
  'Items will appear here once agents produce deliverables.': 'Item akan dipaparkan di sini sebaik sahaja ejen menghasilkan penghantaran.',
  'All': 'Semua',
  'draft': 'draf',
  'review': 'semakan',
  'approved': 'diluluskan',
  'rejected': 'ditolak',
  'final': 'muktamad',
  'document': 'dokumen',
  'code': 'kod',
  'design': 'reka bentuk',
  'analysis': 'analisis',
  'plan': 'rancangan',
  'report': 'laporan',
  'Filter by status': 'Tapis mengikut status',
  'No {status} items found': 'Tiada item {status} ditemui',
  'v{version}': 'v{version}',
  'Close': 'tutup',
  'Download': 'Muat turun',
} as const
