import { en } from './en'

type I18n = Record<(typeof en)[number], string>

/** Unreviewed machine-translation draft: my. Needs native review. */
export const my: I18n = {
  'Library': 'စာကြည့်တိုက်',
  'All deliverables generated by your agents': 'သင့်အေးဂျင့်များမှ ထုတ်ပေးနိုင်သော ပစ္စည်းအားလုံး',
  'Loading library…': 'ဒစ်ဂျစ်တိုက်ကို ဖွင့်နေသည်…',
  'No items yet': 'ပစ္စည်းမရသေးပါ။',
  'Items will appear here once agents produce deliverables.': 'အေးဂျင့်များ ပေးပို့နိုင်သည်နှင့် ကုန်ပစ္စည်းများ ဤနေရာတွင် ပေါ်လာပါမည်။',
  'All': 'အားလုံး',
  'draft': 'အကြမ်း',
  'review': 'သုံးသပ်ချက်',
  'approved': 'အတည်ပြုခဲ့သည်။',
  'rejected': 'ငြင်းပယ်ခဲ့သည်။',
  'final': 'နောက်ဆုံး',
  'document': 'စာရွက်စာတမ်း',
  'code': 'ကုဒ်',
  'design': 'ဒီဇိုင်း',
  'analysis': 'ခွဲခြမ်းစိတ်ဖြာ',
  'plan': 'အစီအစဉ်',
  'report': 'အစီရင်ခံစာ',
  'Filter by status': 'အခြေအနေအလိုက် စစ်ထုတ်ပါ။',
  'No {status} items found': '{status} မည်သည့်အရာမျှ မတွေ့ပါ။',
  'v{version}': 'v{version}',
  'Close': 'ပိတ်လိုက်',
  'Download': 'ဒေါင်းလုဒ်လုပ်ပါ။',
} as const
