import { en } from './en'

type I18n = Record<(typeof en)[number], string>

/** Unreviewed machine-translation draft: pl. Needs native review. */
export const pl: I18n = {
  'Library': 'Biblioteka',
  'All deliverables generated by your agents': 'Wszystkie produkty generowane przez Twoich agentów',
  'Loading library…': 'Ładowanie biblioteki…',
  'No items yet': 'Nie ma jeszcze żadnych elementów',
  'Items will appear here once agents produce deliverables.': 'Przedmioty pojawią się tutaj, gdy agenci wyprodukują produkty.',
  'All': 'Wszystko',
  'draft': 'projekt',
  'review': 'recenzja',
  'approved': 'zatwierdzony',
  'rejected': 'odrzucony',
  'final': 'ostateczny',
  'document': 'dokument',
  'code': 'kod',
  'design': 'projekt',
  'analysis': 'analiza',
  'plan': 'planuj',
  'report': 'raport',
  'Filter by status': 'Filtruj według stanu',
  'No {status} items found': 'Nie znaleziono elementów {status}',
  'v{version}': 'v{version}',
  'Close': 'Zamknij',
  'Download': 'Pobierz',
} as const
