import { en } from './en'

type I18n = Record<(typeof en)[number], string>

/** Unreviewed machine-translation draft: pt. Needs native review. */
export const pt: I18n = {
  'Library': 'Biblioteca',
  'All deliverables generated by your agents': 'Todas as entregas geradas por seus agentes',
  'Loading library…': 'Carregando biblioteca…',
  'No items yet': 'Nenhum item ainda',
  'Items will appear here once agents produce deliverables.': 'Os itens aparecerão aqui assim que os agentes produzirem as entregas.',
  'All': 'Todos',
  'draft': 'rascunho',
  'review': 'revisão',
  'approved': 'aprovado',
  'rejected': 'rejeitado',
  'final': 'final',
  'document': 'documento',
  'code': 'código',
  'design': 'projeto',
  'analysis': 'análise',
  'plan': 'planejar',
  'report': 'relatório',
  'Filter by status': 'Filtrar por status',
  'No {status} items found': 'Nenhum item {status} encontrado',
  'v{version}': 'v{version}',
  'Close': 'Fechar',
  'Download': 'Baixar',
} as const
