import { en } from './en'

type I18n = Record<(typeof en)[number], string>

/** Unreviewed machine-translation draft: su. Needs native review. */
export const su: I18n = {
  'Library': 'Perpustakaan',
  'All deliverables generated by your agents': 'Sadaya kiriman anu dihasilkeun ku agén anjeun',
  'Loading library…': 'Ngamuat perpustakaan…',
  'No items yet': 'Euweuh barang acan',
  'Items will appear here once agents produce deliverables.': 'Barang bakal muncul di dieu saatos agén ngahasilkeun kiriman.',
  'All': 'Sadayana',
  'draft': 'draf',
  'review': 'resensi',
  'approved': 'disatujuan',
  'rejected': 'ditolak',
  'final': 'ahir',
  'document': 'dokumén',
  'code': 'kodeu',
  'design': 'rarancang',
  'analysis': 'analisis',
  'plan': 'rencana',
  'report': 'laporan',
  'Filter by status': 'Nyaring dumasar status',
  'No {status} items found': 'Teu aya barang {status} anu kapendak',
  'v{version}': 'v{version}',
  'Close': 'Tutup',
  'Download': 'Ngundeur',
} as const
