import { en } from './en'

type I18n = Record<(typeof en)[number], string>

/** Unreviewed machine-translation draft: th. Needs native review. */
export const th: I18n = {
  'Library': 'ห้องสมุด',
  'All deliverables generated by your agents': 'การส่งมอบทั้งหมดที่สร้างโดยตัวแทนของคุณ',
  'Loading library…': 'กำลังโหลดไลบรารี...',
  'No items yet': 'ยังไม่มีรายการ',
  'Items will appear here once agents produce deliverables.': 'สินค้าจะปรากฏที่นี่เมื่อตัวแทนผลิตสินค้าที่ส่งมอบ',
  'All': 'ทั้งหมด',
  'draft': 'ร่าง',
  'review': 'ทบทวน',
  'approved': 'ได้รับการอนุมัติ',
  'rejected': 'ถูกปฏิเสธ',
  'final': 'สุดท้าย',
  'document': 'เอกสาร',
  'code': 'รหัส',
  'design': 'การออกแบบ',
  'analysis': 'การวิเคราะห์',
  'plan': 'แผน',
  'report': 'รายงาน',
  'Filter by status': 'กรองตามสถานะ',
  'No {status} items found': 'ไม่พบรายการ {status}',
  'v{version}': 'v{version}',
  'Close': 'ปิด',
  'Download': 'ดาวน์โหลด',
} as const
