import { en } from './en'

type I18n = Record<(typeof en)[number], string>

/** Unreviewed machine-translation draft: ur. Needs native review. */
export const ur: I18n = {
  'Library': 'لائبریری',
  'All deliverables generated by your agents': 'آپ کے ایجنٹوں کے ذریعہ تیار کردہ تمام ڈیلیوریبلز',
  'Loading library…': 'لائبریری لوڈ ہو رہی ہے…',
  'No items yet': 'ابھی تک کوئی آئٹمز نہیں ہیں۔',
  'Items will appear here once agents produce deliverables.': 'ایجنٹوں کی طرف سے ڈیلیوری ایبلز تیار کرنے کے بعد اشیاء یہاں ظاہر ہوں گی۔',
  'All': 'تمام',
  'draft': 'مسودہ',
  'review': 'جائزہ لیں',
  'approved': 'منظور شدہ',
  'rejected': 'مسترد کر دیا',
  'final': 'حتمی',
  'document': 'دستاویز',
  'code': 'کوڈ',
  'design': 'ڈیزائن',
  'analysis': 'تجزیہ',
  'plan': 'منصوبہ',
  'report': 'رپورٹ',
  'Filter by status': 'حیثیت کے لحاظ سے فلٹر کریں۔',
  'No {status} items found': 'کوئی {status} آئٹمز نہیں ملے',
  'v{version}': 'v{version}',
  'Close': 'بند',
  'Download': 'ڈاؤن لوڈ کریں۔',
} as const
