import { en } from './en'

type I18n = Record<(typeof en)[number], string>

/** Unreviewed machine-translation draft: vi. Needs native review. */
export const vi: I18n = {
  'Library': 'Thư viện',
  'All deliverables generated by your agents': 'Tất cả các sản phẩm bàn giao do đại lý của bạn tạo ra',
  'Loading library…': 'Đang tải thư viện…',
  'No items yet': 'Chưa có mục nào',
  'Items will appear here once agents produce deliverables.': 'Các mặt hàng sẽ xuất hiện ở đây sau khi đại lý sản xuất các sản phẩm giao được.',
  'All': 'Tất cả',
  'draft': 'dự thảo',
  'review': 'đánh giá',
  'approved': 'đã được phê duyệt',
  'rejected': 'bị từ chối',
  'final': 'cuối cùng',
  'document': 'tài liệu',
  'code': 'mã',
  'design': 'thiết kế',
  'analysis': 'phân tích',
  'plan': 'kế hoạch',
  'report': 'báo cáo',
  'Filter by status': 'Lọc theo trạng thái',
  'No {status} items found': 'Không tìm thấy mục {status} nào',
  'v{version}': 'v{version}',
  'Close': 'Đóng',
  'Download': 'Tải xuống',
} as const
