import { en } from './en'

type I18n = Record<(typeof en)[number], string>

/** Unreviewed machine-translation draft: yue. Needs native review. */
export const yue: I18n = {
  'Library': '圖書館',
  'All deliverables generated by your agents': '由你嘅代理產生嘅所有交付品',
  'Loading library…': '載入緊圖書館 …',
  'No items yet': '仲未有任何物品',
  'Items will appear here once agents produce deliverables.': '當代理商生產出交付品之後，項目就會喺呢度出現。',
  'All': '全部',
  'draft': '草稿',
  'review': '評論',
  'approved': '批准咗',
  'rejected': '拒絕咗',
  'final': '最後',
  'document': '文件',
  'code': '代碼',
  'design': '設計',
  'analysis': '分析',
  'plan': '計劃',
  'report': '報告',
  'Filter by status': '按狀態過濾',
  'No {status} items found': '未找到 {status} 商品',
  'v{version}': 'v{version}',
  'Close': '閂咗',
  'Download': '下載',
} as const
