import { en } from './en'

type I18n = Record<(typeof en)[number], string>

/** Unreviewed machine-translation draft: zh-CN. Needs native review. */
export const zh_CN: I18n = {
  'Library': '图书馆',
  'All deliverables generated by your agents': '您的代理生成的所有可交付成果',
  'Loading library…': '正在加载库...',
  'No items yet': '还没有商品',
  'Items will appear here once agents produce deliverables.': '一旦代理产生可交付成果，项目就会出现在此处。',
  'All': '全部',
  'draft': '草案',
  'review': '评论',
  'approved': '已批准',
  'rejected': '被拒绝',
  'final': '决赛',
  'document': '文件',
  'code': '代码',
  'design': '设计',
  'analysis': '分析',
  'plan': '计划',
  'report': '报告',
  'Filter by status': '按状态过滤',
  'No {status} items found': '未找到 {status} 项目',
  'v{version}': 'v{version}',
  'Close': '关闭',
  'Download': '下载',
} as const
