import { en } from './en'

type I18n = Record<(typeof en)[number], string>

/** Unreviewed machine-translation draft: zh-TW. Needs native review. */
export const zh_TW: I18n = {
  'Library': '圖書館',
  'All deliverables generated by your agents': '您的代理商產生的所有可交付成果',
  'Loading library…': '正在加載庫...',
  'No items yet': '還沒有商品',
  'Items will appear here once agents produce deliverables.': '一旦代理商產生可交付成果，專案就會出現在此。',
  'All': '全部',
  'draft': '草案',
  'review': '評論',
  'approved': '已批准',
  'rejected': '被拒絕',
  'final': '決賽',
  'document': '文件',
  'code': '程式碼',
  'design': '設計',
  'analysis': '分析',
  'plan': '計劃',
  'report': '報告',
  'Filter by status': '按狀態過濾',
  'No {status} items found': '未找到 {status} 項目',
  'v{version}': 'v{version}',
  'Close': '關閉',
  'Download': '下載',
} as const
